AllCops:
  Exclude:
    - bin/{rake,rspec,rubocop}
    - db/schema.rb
  NewCops: enable

Layout/ArgumentAlignment:
  Enabled: false

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - spec/**/*_spec.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
